# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Cell Score"
license = "MIT"
licenselink = "https://github.com/BoyPlankton/hugo-cell-score/blob/main/LICENSE"
description = "This is a Hugo theme for displaying historical cell score data for the AR game Ingress."
homepage = "https://github.com/BoyPlankton/hugo-cell-score"
tags = ["ingress"]
features = []
min_version = "0.41.0"

[author]
  name = "Vincent Marcus"
  homepage = "https://github.com/BoyPlankton"

